### ISSUE TITLE
QA for USAF Networked Computers

### ISSUE THREAD

**Issue by Dynathy** [22arw/airshow#22]
Icons appear colorized rather than black and white/ colorized while hovering.
All banner and images from picsum will not load.
Cards not properly spaced, causing overflow on the performers tab. 

Other issues may be added below.

**Comment by kevinfalting** [comment]
These are problems found using Internet Explorer and/or on `.mil` computers.

- [ ] Icons appear colorized rather than black and white/colorized while hovering on IE.
- [ ] All images from picsum will not load.
- [ ] On `/performers` the cards are not spacing properly on Internet Explorer.
- [ ] Brightness filters on Internet Explorer are not working on banner images.
- [ ] Brightness filter on landing image isn't working on IE.
- [ ] On the landing component, the title box loses `padding-top` on Firefox and Edge browsers. This may actually be a media query problem if it isn't changing the padding or margin levels depending on the screen size.

**Comment by kevinfalting** [comment]
The changes made on the above commit only apply to `/performers`.
